server:
  servlet:
    context-path: /tunan


spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: juan970907!@#
    url: jdbc:mysql://aliyun:3306/study?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


---
server:
  port: 9997

spring:
  profiles: dev

---
server:
  port: 9998

spring:
  profiles: prod