server:
  servlet:
    context-path: /tunan


spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  jpa:
    hibernate:
      #            如果表不存在或已更新,则自动创建/更新
      ddl-auto: update
      #            显示sql语句
      show-sql: true
  datasource:
    username: root
    password: juan970907!@#
    url: jdbc:mysql://aliyun:3306/study?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


mycart:
  name: BYD
  price: 100000

---
server:
  port: 9997

spring:
  profiles: dev

---
server:
  port: 9998

spring:
  profiles: prod